# Generated by Django 4.2.8 on 2023-12-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Товар', max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL:')),
                ('description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Описание')),
                ('price', models.IntegerField(default=999999, verbose_name='Цена')),
                ('photo', models.FileField(blank=True, default='', upload_to='goods/', verbose_name='Фото товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_num', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Номер заказа')),
                ('order_owner', models.CharField(default='Аноним', max_length=255, verbose_name='Имя заказчика')),
                ('owner_data', models.TextField(default='г. Москва, улица Пушкина, дом Колотушкина', max_length=1000, verbose_name='Доп. информация')),
                ('order_sum', models.IntegerField(default=0, editable=False, verbose_name='Сумма заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_num'],
            },
        ),
        migrations.CreateModel(
            name='Orders_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.goods', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.orders', verbose_name='Номер заказа')),
            ],
            options={
                'verbose_name': 'Данные по заказу',
                'verbose_name_plural': 'Данные по заказам',
                'ordering': ['-order'],
            },
        ),
    ]
