# Generated by Django 4.2.8 on 2023-12-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_key',
            field=models.CharField(default='', editable=False, max_length=32, verbose_name='Ключ заказа'),
        ),
    ]
