# Generated by Django 4.2.8 on 2023-12-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orders_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_key',
            field=models.CharField(default='gy49SUGj4DHuavsddnnsaXfCiDkvx59t', editable=False, max_length=32, verbose_name='Ключ заказа'),
        ),
    ]
