# Generated by Django 4.2.8 on 2023-12-27 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_orders_order_key_alter_orders_order_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders_Data',
            new_name='OrdersData',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_key',
            field=models.CharField(default='Ox6SkEmRU7bUGOrV6sSjjH8YqgR0UvVM', editable=False, max_length=32, verbose_name='Ключ заказа'),
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины пользователей',
            },
        ),
    ]
