# Generated by Django 4.2.8 on 2024-01-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_orders_order_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_key',
            field=models.CharField(default='CbBNAUMz3n3qHholTXJ0YKUizuwW97do', editable=False, max_length=32, verbose_name='Ключ заказа'),
        ),
    ]
